services: [docker]

before_script:
  - docker version
  - docker login --email=$DOCKER_EMAIL --username=$DOCKER_USERNAME --password=$DOCKER_PASSWORD
  # Ancient make binary at TravisCI doesn't support indentation with spaces
  - unexpand -t 4 Makefile > Makefile.tmp && mv Makefile.tmp Makefile

script:
  - make test

after_success:
  - if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then docker push domcode/raffler; fi
