services: [docker]

before_script:
  - docker version
  - if [ "$DOCKER_USERNAME" != "" ]; then docker login --username=$DOCKER_USERNAME --password=$DOCKER_PASSWORD; fi
  # Ancient make binary at TravisCI doesn't support indentation with spaces
  - unexpand -t 4 Makefile > Makefile.tmp && mv Makefile.tmp Makefile

script:
  - make test

after_success:
  - if [ "$DOCKER_USERNAME" != "" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then docker push domcode/raffler; fi
