services: [docker]

matrix:
  allow_failures:
    - env: RAFFLER=annabaas-java
    - env: RAFFLER=annabaas-kotlin
    - env: RAFFLER=aochagavia-rust
    - env: RAFFLER=arnovr-pascal
    - env: RAFFLER=arnovr-squirrel
    - env: RAFFLER=arothuis-dlang
    - env: RAFFLER=basbl-elixir
    - env: RAFFLER=basbl-zsh
    - env: RAFFLER=bauro-ansible
    - env: RAFFLER=bauro-haproxy
    - env: RAFFLER=bkors-java-spring-boot-enterprice
    - env: RAFFLER=borkdude-cljs-node-lumo
    - env: RAFFLER=borkdude-clojure
    - env: RAFFLER=breun-ansible
    - env: RAFFLER=breun-groovy
    - env: RAFFLER=breun-java
    - env: RAFFLER=breun-kotlin
    - env: RAFFLER=breun-python
    - env: RAFFLER=daniellemccool-r
    - env: RAFFLER=dennisdegreef-actionscript3
    - env: RAFFLER=Dockerfile
    - env: RAFFLER=drvanr-FORTRAN
    - env: RAFFLER=drvanr-lua
    - env: RAFFLER=duijf-julia
    - env: RAFFLER=erikaheidi-c
    - env: RAFFLER=example_names
    - env: RAFFLER=frankdejonge-rust
    - env: RAFFLER=jaytaph-awk
    - env: RAFFLER=jaytaph-bash
    - env: RAFFLER=jaytaph-bootsector-asm
    - env: RAFFLER=jaytaph-php7-extension
    - env: RAFFLER=jaytaph-php-legacy
    - env: RAFFLER=jaytaph-saffire
    - env: RAFFLER=jeroenheijmans-netcore2
    - env: RAFFLER=jeroenvdgulik-java
    - env: RAFFLER=kaeufl-brainfuck
    - env: RAFFLER=kilte-python3
    - env: RAFFLER=lucasvanlierop-agc-assembly
    - env: RAFFLER=lucasvanlierop-cobol
    - env: RAFFLER=markredeman-cpp
    - env: RAFFLER=mathiasverraes-erlang
    - env: RAFFLER=mathiasverraes-lambdalicious
    - env: RAFFLER=mattp-whitespace
    - env: RAFFLER=michielrook-scala-akka
    - env: RAFFLER=nickspelt-html
    - env: RAFFLER=nickspelt-node
    - env: RAFFLER=ramondelafuente-php-array-insanity
    - env: RAFFLER=rdohms-lolcode
    - env: RAFFLER=rdohms-lua
    - env: RAFFLER=remyhonig-elisp
    - env: RAFFLER=rjkip-bash
    - env: RAFFLER=rjkip-drvanr-pony
    - env: RAFFLER=rjkip-elixir
    - env: RAFFLER=rjkip-nim
    - env: RAFFLER=rjkip-rust
    - env: RAFFLER=rosstuck-php
    - env: RAFFLER=rpkamp-go
    - env: RAFFLER=scato-elm
    - env: RAFFLER=scato-glitch
    - env: RAFFLER=scato-haxe
    - env: RAFFLER=sgoettschkes-haskell
    - env: RAFFLER=shawnmccool-scala
    - env: RAFFLER=snoek09-perl
    - env: RAFFLER=steazzalini-cmake
    - env: RAFFLER=steazzalini-mysql
    - env: RAFFLER=steazzalini-nodejs
    - env: RAFFLER=steazzalini-ocaml
    - env: RAFFLER=stelian-python
    - env: RAFFLER=stelian-python-objective
    - env: RAFFLER=stelian-ruby
    - env: RAFFLER=turanct-scheme
    - env: RAFFLER=winkbrace-dos-batch
    - env: RAFFLER=wjzijderveld-c
    - env: RAFFLER=wjzijderveld-go
    - env: RAFFLER=wyrihaximus-php7

before_script:
  # Ancient make binary at TravisCI doesn't support indentation with spaces
  - unexpand -t 4 Makefile > Makefile.tmp && mv Makefile.tmp Makefile

script:
  - make test
  #- if [ "$TRAVIS_PULL_REQUEST" != "false" ] && [ "$TRAVIS_BRANCH" == "master" ]; then make test-changed; else make test; fi

after_success:
  - if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then docker login --username=$DOCKER_USERNAME --password=$DOCKER_PASSWORD && docker push domcode/raffler; fi
