---
- name: Check if the input file exist
  stat: path={{ names_file }}
  register: input_file

- name: Trow debug message to notify that the input file does not exist
  debug: msg="The input file {{ names_file }} does not exist"
  when: input_file.stat.exists == False

- name: register all the names
  command: cat {{ names_file }}
  register: names
  when: input_file.stat.exists != False

- name: And the winner is
  debug: msg="{{ item }}"
  with_random_choice: names.stdout_lines
  when: input_file.stat.exists != False